vocabulary.md
Not a native english speaker here, but I think this reads better.
=> Tiny typo on vocabulary.md

where-we-work.md
`The most of people` → `Most people`
=> Fixed typo in working from home text

benefits-and-perks.md
"An employee who has just been" rather than "An employee who've just been".
=> Trivial: grammar: agreement-in-number

moonlighting.md
=> Fix typo (add missing "to")

README.md
When I first read “slowly boiled frogs”, I read it as “slowly boiled-frogs” — which didn’t make any sense to me, causing mental friction. After re-reading those words 2–3 times, I realized it should be “slowly-boiled frogs”.
Hyphenated the compound-modifier to add clarity and reduce mental friction.
=> Hyphenated a compound-modifier.

moonlighting.md
Just a nitpicky spelling change.
=> Changing "You've" to "You're"

vocabulary.md
No one comes into Basecamp knowing this acronym and people often wait months to ask. I’d welcome any edits to the definition.
=> Explain acronym: PDI

titles-for-programmers.md
Apparently I follow your company changes pretty closely. ;)
https://m.signalvnoise.com/basecamp-doesnt-employ-anyone-in-san-francisco-but-now-we-pay-everyone-as-though-all-did-3ee87013cfc2
=> Update to SF pay scale instead of Chicago

orgchart.md
…because it should be perfect :)
=> Use proper apostrophes

orgchart.md
Offering a small change if you're interested. Thanks for sharing the handbook.
=> Small change to complete the sentence "on top of"

what-we-stand-for.md
Speaking of poetry, it seems fitting that the eight word sentence listing the number of words to avoid could be easily self referential.
=> Updates excessive word count to 8

making-a-career.md, titles-for-ops.md
=> Opschanges

orgchart.md
Hey Andrea - I think I saw in Basecamp HQ that Blake is now full-time with Basecamp, right?
(P.S. the back-and-forth in commits is because at first I made a commit in the master branch before figuring out how to make a new branch for possible_updates so that you can review / sanity check before they're published!)
=> Possible updates

product-histories.md
Hi David - I've made a few tweaks to the Product History page based on what I found in the SvN blogs.
=> Product history

performance-plans.md
For additional context, see: https://getitwriteonline.com/articles/bi-or-semi/
=> Reduce ambiguity with "bi-yearly"

orgchart.md
=> Update QA section

benefits-and-perks.md
Dropping the profit sharing program since it was discontinued this year.
=> Remove profit sharing program.

orgchart.md
Reflect the new team structure.
=> Reorganize around the Ops team split.

what-we-stand-for.md
=> Fix typo (s/laticework/latticework)

titles-for-data.md
Based on conversation with DHH. Goal is to tailor the bullets for the Data track while avoiding implications that programming fluency in Rails, etc. is expected or necessary.
=> propose more detail to Lead and Principal levels

how-we-work.md, making-a-career.md
=> Fix minor typos

how-we-work.md
Just something small I noticed while reading through the handbook 😄
=> Use "are" instead of "is" for pluralized words

getting-started.md
Communicate that internal links are private via the lock emoji.
=> Note that Shipshape links are private.

orgchart.md
Also add consistency to development team paragraphs.
=> Update RF team

what-we-stand-for.md
I think what is meant is
- "everyone is accountable"
If using the possessive case, it should be something like: 
- "it's everyone's accountability"
And btw, thanks for a great read!
=> Replace incorrect contraction

moonlighting.md
=> Fix grammar + comma nit in moonlighting.md

orgchart.md
Updates the org chart to reflect the changes to the design team structure.
=> marketing design -> Brand & Experience

our-rituals.md
It is my understanding that Meetups are not always hosted in Chicago these days.
=> Don't specify location of Meetups

product-histories.md
I had some difficulty understanding the sentence :)
=> Improve a sentence's clarity on the Product History Page
